### ISSUE TITLE
What is the license?

### ISSUE THREAD

**Issue by Ippo343** [JeremiSharkboy/Radio-Button-WPF-Style#1]
Hi, I'd like to re-use your style in a project I'm working on, but without an explicit license I'm afraid I can't do that. I was wondering if you could please add an explicit license to the repo.

Thanks!

**Comment by Sharkboy-j** [comment]
> Hi, I'd like to re-use your style in a project I'm working on, but without an explicit license I'm afraid I can't do that. I was wondering if you could please add an explicit license to the repo.
> 
> Thanks!

Free to use :)
